/**
 * Generates a NetBird network group id from manifest and network keys.
 */
export namespace NetworkGroupId {
    /**
     * Builds a stable network group id for a manifest network.
     * 
     * @param manifestName Manifest name declared in compose metadata
     * @param networkKey Network key from the manifest networks map
     * @returns Network group id in the form manifestName-networkKey
     */
    export function build(manifestName: string, networkKey: string): string {
        return `${manifestName}-${networkKey}`;
    }

    /**
     * Parses a network group id back into manifest and network parts.
     * 
     * @param networkGroupId Network group id generated by {@link build}
     * @returns Parsed manifest and network key when the id is valid
     */
    export function parse(networkGroupId: string): { manifestName: string; networkKey: string } | null {
        const separatorIndex = networkGroupId.indexOf("-");

        if (separatorIndex <= 0 || separatorIndex === networkGroupId.length - 1) {
            return null;
        }

        return {
            manifestName: networkGroupId.slice(0, separatorIndex),
            networkKey: networkGroupId.slice(separatorIndex + 1)
        };
    }
}
