#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
NB_DIR="$ROOT/infra/netbird"
cd "$NB_DIR"

if [[ -z "${NETBIRD_DOMAIN:-}" ]]; then
    echo "NETBIRD_DOMAIN is required (e.g. vpn.example.com)." >&2
    echo "For local dogfood without a public domain, use your machine IP or a hosts entry." >&2
    exit 1
fi

if [[ "$NETBIRD_DOMAIN" == "netbird.example.com" ]]; then
    echo "NETBIRD_DOMAIN cannot be netbird.example.com." >&2
    exit 1
fi

NETBIRD_HTTP_PROTOCOL="${NETBIRD_HTTP_PROTOCOL:-http}"
NETBIRD_PORT="${NETBIRD_PORT:-${NETBIRD_SERVER_PORT:-9081}}"
NETBIRD_STUN_PORT="${NETBIRD_STUN_PORT:-3478}"
NETBIRD_RELAY_AUTH_SECRET="$(openssl rand -base64 32 | tr -d '=')"
DATASTORE_ENCRYPTION_KEY="$(openssl rand -base64 32)"
PUBLIC_API_URL="${NETBIRD_HTTP_PROTOCOL}://${NETBIRD_DOMAIN}"
if [[ "$NETBIRD_HTTP_PROTOCOL" == "http" && "$NETBIRD_PORT" != "80" ]]; then
    PUBLIC_API_URL="${PUBLIC_API_URL}:${NETBIRD_PORT}"
fi

cat > config.yaml <<EOF
# Generated by dogfood/scripts/init-netbird-config.sh

server:
  listenAddress: ":80"
  exposedAddress: "${PUBLIC_API_URL}"
  stunPorts:
    - ${NETBIRD_STUN_PORT}
  metricsPort: 9090
  healthcheckAddress: ":9000"
  logLevel: "info"
  logFile: "console"

  authSecret: "${NETBIRD_RELAY_AUTH_SECRET}"
  dataDir: "/var/lib/netbird"

  auth:
    issuer: "${PUBLIC_API_URL}/oauth2"
    signKeyRefreshEnabled: true
    dashboardRedirectURIs:
      - "${PUBLIC_API_URL}/nb-auth"
      - "${PUBLIC_API_URL}/nb-silent-auth"
    cliRedirectURIs:
      - "http://localhost:53000/"

  store:
    engine: "sqlite"
    encryptionKey: "${DATASTORE_ENCRYPTION_KEY}"
EOF

cat > dashboard.env <<EOF
NETBIRD_MGMT_API_ENDPOINT=${PUBLIC_API_URL}
NETBIRD_MGMT_GRPC_API_ENDPOINT=${PUBLIC_API_URL}
AUTH_AUDIENCE=netbird-dashboard
AUTH_CLIENT_ID=netbird-dashboard
AUTH_CLIENT_SECRET=
AUTH_AUTHORITY=${PUBLIC_API_URL}/oauth2
USE_AUTH0=false
AUTH_SUPPORTED_SCOPES=openid profile email groups
AUTH_REDIRECT_URI=/nb-auth
AUTH_SILENT_REDIRECT_URI=/nb-silent-auth
NGINX_SSL_PORT=443
LETSENCRYPT_DOMAIN=none
EOF

echo "NetBird config written to dogfood/infra/netbird/ (config.yaml, dashboard.env)."
echo "Management API (host): ${PUBLIC_API_URL}/api"
echo "Control plane (Docker network): http://netbird-server/api"
echo "Credentials are bootstrapped automatically by the control plane on first startup."
