services:
    dashboard:
        image: netbirdio/dashboard:v2.90.0
        container_name: netbird-dashboard
        restart: unless-stopped
        networks:
            - netbird
        env_file:
            - dashboard.env

    netbird-server:
        image: netbirdio/netbird-server:0.73.2
        container_name: netbird-server
        restart: unless-stopped
        environment:
            NB_SETUP_PAT_ENABLED: "true"
        networks:
            - netbird
        ports:
            - "${NETBIRD_SERVER_PORT:-9081}:80"
            - "3478:3478/udp"
        volumes:
            - netbird_data:/var/lib/netbird
            - ./config.yaml:/etc/netbird/config.yaml
        command:
            - --config
            - /etc/netbird/config.yaml

volumes:
    netbird_data:

networks:
    netbird:
